// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package org.eclipse.ecf.provider.etcd3.grpc.api;

public interface AlarmMemberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.AlarmMember)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * memberID is the ID of the member associated with the raised alarm.
   * </pre>
   *
   * <code>uint64 memberID = 1;</code>
   * @return The memberID.
   */
  long getMemberID();

  /**
   * <pre>
   * alarm is the type of alarm which has been raised.
   * </pre>
   *
   * <code>.etcdserverpb.AlarmType alarm = 2;</code>
   * @return The enum numeric value on the wire for alarm.
   */
  int getAlarmValue();
  /**
   * <pre>
   * alarm is the type of alarm which has been raised.
   * </pre>
   *
   * <code>.etcdserverpb.AlarmType alarm = 2;</code>
   * @return The alarm.
   */
  org.eclipse.ecf.provider.etcd3.grpc.api.AlarmType getAlarm();
}
