// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package org.eclipse.ecf.provider.etcd3.grpc.api;

/**
 * Protobuf type {@code etcdserverpb.AuthRoleGrantPermissionRequest}
 */
public final class AuthRoleGrantPermissionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:etcdserverpb.AuthRoleGrantPermissionRequest)
    AuthRoleGrantPermissionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AuthRoleGrantPermissionRequest.newBuilder() to construct.
  private AuthRoleGrantPermissionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AuthRoleGrantPermissionRequest() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AuthRoleGrantPermissionRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_AuthRoleGrantPermissionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_AuthRoleGrantPermissionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest.class, org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * name is the name of the role which will be granted the permission.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * name is the name of the role which will be granted the permission.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERM_FIELD_NUMBER = 2;
  private org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission perm_;
  /**
   * <pre>
   * perm is the permission to grant to the role.
   * </pre>
   *
   * <code>.authpb.Permission perm = 2;</code>
   * @return Whether the perm field is set.
   */
  @java.lang.Override
  public boolean hasPerm() {
    return perm_ != null;
  }
  /**
   * <pre>
   * perm is the permission to grant to the role.
   * </pre>
   *
   * <code>.authpb.Permission perm = 2;</code>
   * @return The perm.
   */
  @java.lang.Override
  public org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission getPerm() {
    return perm_ == null ? org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission.getDefaultInstance() : perm_;
  }
  /**
   * <pre>
   * perm is the permission to grant to the role.
   * </pre>
   *
   * <code>.authpb.Permission perm = 2;</code>
   */
  @java.lang.Override
  public org.eclipse.ecf.provider.etcd3.grpc.api.auth.PermissionOrBuilder getPermOrBuilder() {
    return perm_ == null ? org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission.getDefaultInstance() : perm_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (perm_ != null) {
      output.writeMessage(2, getPerm());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (perm_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPerm());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest)) {
      return super.equals(obj);
    }
    org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest other = (org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (hasPerm() != other.hasPerm()) return false;
    if (hasPerm()) {
      if (!getPerm()
          .equals(other.getPerm())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasPerm()) {
      hash = (37 * hash) + PERM_FIELD_NUMBER;
      hash = (53 * hash) + getPerm().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code etcdserverpb.AuthRoleGrantPermissionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:etcdserverpb.AuthRoleGrantPermissionRequest)
      org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_AuthRoleGrantPermissionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_AuthRoleGrantPermissionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest.class, org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest.Builder.class);
    }

    // Construct using org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      perm_ = null;
      if (permBuilder_ != null) {
        permBuilder_.dispose();
        permBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_AuthRoleGrantPermissionRequest_descriptor;
    }

    @java.lang.Override
    public org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest getDefaultInstanceForType() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest build() {
      org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest buildPartial() {
      org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest result = new org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.perm_ = permBuilder_ == null
            ? perm_
            : permBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest) {
        return mergeFrom((org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest other) {
      if (other == org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasPerm()) {
        mergePerm(other.getPerm());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getPermFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * name is the name of the role which will be granted the permission.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * name is the name of the role which will be granted the permission.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * name is the name of the role which will be granted the permission.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name is the name of the role which will be granted the permission.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name is the name of the role which will be granted the permission.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission perm_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission, org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission.Builder, org.eclipse.ecf.provider.etcd3.grpc.api.auth.PermissionOrBuilder> permBuilder_;
    /**
     * <pre>
     * perm is the permission to grant to the role.
     * </pre>
     *
     * <code>.authpb.Permission perm = 2;</code>
     * @return Whether the perm field is set.
     */
    public boolean hasPerm() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * perm is the permission to grant to the role.
     * </pre>
     *
     * <code>.authpb.Permission perm = 2;</code>
     * @return The perm.
     */
    public org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission getPerm() {
      if (permBuilder_ == null) {
        return perm_ == null ? org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission.getDefaultInstance() : perm_;
      } else {
        return permBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * perm is the permission to grant to the role.
     * </pre>
     *
     * <code>.authpb.Permission perm = 2;</code>
     */
    public Builder setPerm(org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission value) {
      if (permBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        perm_ = value;
      } else {
        permBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * perm is the permission to grant to the role.
     * </pre>
     *
     * <code>.authpb.Permission perm = 2;</code>
     */
    public Builder setPerm(
        org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission.Builder builderForValue) {
      if (permBuilder_ == null) {
        perm_ = builderForValue.build();
      } else {
        permBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * perm is the permission to grant to the role.
     * </pre>
     *
     * <code>.authpb.Permission perm = 2;</code>
     */
    public Builder mergePerm(org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission value) {
      if (permBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          perm_ != null &&
          perm_ != org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission.getDefaultInstance()) {
          getPermBuilder().mergeFrom(value);
        } else {
          perm_ = value;
        }
      } else {
        permBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * perm is the permission to grant to the role.
     * </pre>
     *
     * <code>.authpb.Permission perm = 2;</code>
     */
    public Builder clearPerm() {
      bitField0_ = (bitField0_ & ~0x00000002);
      perm_ = null;
      if (permBuilder_ != null) {
        permBuilder_.dispose();
        permBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * perm is the permission to grant to the role.
     * </pre>
     *
     * <code>.authpb.Permission perm = 2;</code>
     */
    public org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission.Builder getPermBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getPermFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * perm is the permission to grant to the role.
     * </pre>
     *
     * <code>.authpb.Permission perm = 2;</code>
     */
    public org.eclipse.ecf.provider.etcd3.grpc.api.auth.PermissionOrBuilder getPermOrBuilder() {
      if (permBuilder_ != null) {
        return permBuilder_.getMessageOrBuilder();
      } else {
        return perm_ == null ?
            org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission.getDefaultInstance() : perm_;
      }
    }
    /**
     * <pre>
     * perm is the permission to grant to the role.
     * </pre>
     *
     * <code>.authpb.Permission perm = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission, org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission.Builder, org.eclipse.ecf.provider.etcd3.grpc.api.auth.PermissionOrBuilder> 
        getPermFieldBuilder() {
      if (permBuilder_ == null) {
        permBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission, org.eclipse.ecf.provider.etcd3.grpc.api.auth.Permission.Builder, org.eclipse.ecf.provider.etcd3.grpc.api.auth.PermissionOrBuilder>(
                getPerm(),
                getParentForChildren(),
                isClean());
        perm_ = null;
      }
      return permBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:etcdserverpb.AuthRoleGrantPermissionRequest)
  }

  // @@protoc_insertion_point(class_scope:etcdserverpb.AuthRoleGrantPermissionRequest)
  private static final org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest();
  }

  public static org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthRoleGrantPermissionRequest>
      PARSER = new com.google.protobuf.AbstractParser<AuthRoleGrantPermissionRequest>() {
    @java.lang.Override
    public AuthRoleGrantPermissionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AuthRoleGrantPermissionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthRoleGrantPermissionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.eclipse.ecf.provider.etcd3.grpc.api.AuthRoleGrantPermissionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

