// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package org.eclipse.ecf.provider.etcd3.grpc.api;

/**
 * Protobuf type {@code etcdserverpb.Member}
 */
public final class Member extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:etcdserverpb.Member)
    MemberOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Member.newBuilder() to construct.
  private Member(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Member() {
    name_ = "";
    peerURLs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    clientURLs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Member();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Member(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            iD_ = input.readUInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              peerURLs_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            peerURLs_.add(s);
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              clientURLs_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            clientURLs_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        peerURLs_ = peerURLs_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        clientURLs_ = clientURLs_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_Member_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_Member_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.eclipse.ecf.provider.etcd3.grpc.api.Member.class, org.eclipse.ecf.provider.etcd3.grpc.api.Member.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long iD_;
  /**
   * <pre>
   * ID is the member ID for this member.
   * </pre>
   *
   * <code>uint64 ID = 1;</code>
   * @return The iD.
   */
  @java.lang.Override
  public long getID() {
    return iD_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * name is the human-readable name of the member. If the member is not started, the name will be an empty string.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * name is the human-readable name of the member. If the member is not started, the name will be an empty string.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PEERURLS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList peerURLs_;
  /**
   * <pre>
   * peerURLs is the list of URLs the member exposes to the cluster for communication.
   * </pre>
   *
   * <code>repeated string peerURLs = 3;</code>
   * @return A list containing the peerURLs.
   */
  public com.google.protobuf.ProtocolStringList
      getPeerURLsList() {
    return peerURLs_;
  }
  /**
   * <pre>
   * peerURLs is the list of URLs the member exposes to the cluster for communication.
   * </pre>
   *
   * <code>repeated string peerURLs = 3;</code>
   * @return The count of peerURLs.
   */
  public int getPeerURLsCount() {
    return peerURLs_.size();
  }
  /**
   * <pre>
   * peerURLs is the list of URLs the member exposes to the cluster for communication.
   * </pre>
   *
   * <code>repeated string peerURLs = 3;</code>
   * @param index The index of the element to return.
   * @return The peerURLs at the given index.
   */
  public java.lang.String getPeerURLs(int index) {
    return peerURLs_.get(index);
  }
  /**
   * <pre>
   * peerURLs is the list of URLs the member exposes to the cluster for communication.
   * </pre>
   *
   * <code>repeated string peerURLs = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the peerURLs at the given index.
   */
  public com.google.protobuf.ByteString
      getPeerURLsBytes(int index) {
    return peerURLs_.getByteString(index);
  }

  public static final int CLIENTURLS_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList clientURLs_;
  /**
   * <pre>
   * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
   * </pre>
   *
   * <code>repeated string clientURLs = 4;</code>
   * @return A list containing the clientURLs.
   */
  public com.google.protobuf.ProtocolStringList
      getClientURLsList() {
    return clientURLs_;
  }
  /**
   * <pre>
   * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
   * </pre>
   *
   * <code>repeated string clientURLs = 4;</code>
   * @return The count of clientURLs.
   */
  public int getClientURLsCount() {
    return clientURLs_.size();
  }
  /**
   * <pre>
   * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
   * </pre>
   *
   * <code>repeated string clientURLs = 4;</code>
   * @param index The index of the element to return.
   * @return The clientURLs at the given index.
   */
  public java.lang.String getClientURLs(int index) {
    return clientURLs_.get(index);
  }
  /**
   * <pre>
   * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
   * </pre>
   *
   * <code>repeated string clientURLs = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the clientURLs at the given index.
   */
  public com.google.protobuf.ByteString
      getClientURLsBytes(int index) {
    return clientURLs_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (iD_ != 0L) {
      output.writeUInt64(1, iD_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    for (int i = 0; i < peerURLs_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, peerURLs_.getRaw(i));
    }
    for (int i = 0; i < clientURLs_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clientURLs_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (iD_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, iD_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < peerURLs_.size(); i++) {
        dataSize += computeStringSizeNoTag(peerURLs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPeerURLsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < clientURLs_.size(); i++) {
        dataSize += computeStringSizeNoTag(clientURLs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getClientURLsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.eclipse.ecf.provider.etcd3.grpc.api.Member)) {
      return super.equals(obj);
    }
    org.eclipse.ecf.provider.etcd3.grpc.api.Member other = (org.eclipse.ecf.provider.etcd3.grpc.api.Member) obj;

    if (getID()
        != other.getID()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getPeerURLsList()
        .equals(other.getPeerURLsList())) return false;
    if (!getClientURLsList()
        .equals(other.getClientURLsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getID());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getPeerURLsCount() > 0) {
      hash = (37 * hash) + PEERURLS_FIELD_NUMBER;
      hash = (53 * hash) + getPeerURLsList().hashCode();
    }
    if (getClientURLsCount() > 0) {
      hash = (37 * hash) + CLIENTURLS_FIELD_NUMBER;
      hash = (53 * hash) + getClientURLsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.eclipse.ecf.provider.etcd3.grpc.api.Member prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code etcdserverpb.Member}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:etcdserverpb.Member)
      org.eclipse.ecf.provider.etcd3.grpc.api.MemberOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_Member_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_Member_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.ecf.provider.etcd3.grpc.api.Member.class, org.eclipse.ecf.provider.etcd3.grpc.api.Member.Builder.class);
    }

    // Construct using org.eclipse.ecf.provider.etcd3.grpc.api.Member.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      iD_ = 0L;

      name_ = "";

      peerURLs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      clientURLs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_Member_descriptor;
    }

    @java.lang.Override
    public org.eclipse.ecf.provider.etcd3.grpc.api.Member getDefaultInstanceForType() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.Member.getDefaultInstance();
    }

    @java.lang.Override
    public org.eclipse.ecf.provider.etcd3.grpc.api.Member build() {
      org.eclipse.ecf.provider.etcd3.grpc.api.Member result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.eclipse.ecf.provider.etcd3.grpc.api.Member buildPartial() {
      org.eclipse.ecf.provider.etcd3.grpc.api.Member result = new org.eclipse.ecf.provider.etcd3.grpc.api.Member(this);
      int from_bitField0_ = bitField0_;
      result.iD_ = iD_;
      result.name_ = name_;
      if (((bitField0_ & 0x00000001) != 0)) {
        peerURLs_ = peerURLs_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.peerURLs_ = peerURLs_;
      if (((bitField0_ & 0x00000002) != 0)) {
        clientURLs_ = clientURLs_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.clientURLs_ = clientURLs_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.eclipse.ecf.provider.etcd3.grpc.api.Member) {
        return mergeFrom((org.eclipse.ecf.provider.etcd3.grpc.api.Member)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.eclipse.ecf.provider.etcd3.grpc.api.Member other) {
      if (other == org.eclipse.ecf.provider.etcd3.grpc.api.Member.getDefaultInstance()) return this;
      if (other.getID() != 0L) {
        setID(other.getID());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.peerURLs_.isEmpty()) {
        if (peerURLs_.isEmpty()) {
          peerURLs_ = other.peerURLs_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensurePeerURLsIsMutable();
          peerURLs_.addAll(other.peerURLs_);
        }
        onChanged();
      }
      if (!other.clientURLs_.isEmpty()) {
        if (clientURLs_.isEmpty()) {
          clientURLs_ = other.clientURLs_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureClientURLsIsMutable();
          clientURLs_.addAll(other.clientURLs_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.eclipse.ecf.provider.etcd3.grpc.api.Member parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.eclipse.ecf.provider.etcd3.grpc.api.Member) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long iD_ ;
    /**
     * <pre>
     * ID is the member ID for this member.
     * </pre>
     *
     * <code>uint64 ID = 1;</code>
     * @return The iD.
     */
    @java.lang.Override
    public long getID() {
      return iD_;
    }
    /**
     * <pre>
     * ID is the member ID for this member.
     * </pre>
     *
     * <code>uint64 ID = 1;</code>
     * @param value The iD to set.
     * @return This builder for chaining.
     */
    public Builder setID(long value) {
      
      iD_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID is the member ID for this member.
     * </pre>
     *
     * <code>uint64 ID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearID() {
      
      iD_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * name is the human-readable name of the member. If the member is not started, the name will be an empty string.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * name is the human-readable name of the member. If the member is not started, the name will be an empty string.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * name is the human-readable name of the member. If the member is not started, the name will be an empty string.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name is the human-readable name of the member. If the member is not started, the name will be an empty string.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name is the human-readable name of the member. If the member is not started, the name will be an empty string.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList peerURLs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensurePeerURLsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        peerURLs_ = new com.google.protobuf.LazyStringArrayList(peerURLs_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * peerURLs is the list of URLs the member exposes to the cluster for communication.
     * </pre>
     *
     * <code>repeated string peerURLs = 3;</code>
     * @return A list containing the peerURLs.
     */
    public com.google.protobuf.ProtocolStringList
        getPeerURLsList() {
      return peerURLs_.getUnmodifiableView();
    }
    /**
     * <pre>
     * peerURLs is the list of URLs the member exposes to the cluster for communication.
     * </pre>
     *
     * <code>repeated string peerURLs = 3;</code>
     * @return The count of peerURLs.
     */
    public int getPeerURLsCount() {
      return peerURLs_.size();
    }
    /**
     * <pre>
     * peerURLs is the list of URLs the member exposes to the cluster for communication.
     * </pre>
     *
     * <code>repeated string peerURLs = 3;</code>
     * @param index The index of the element to return.
     * @return The peerURLs at the given index.
     */
    public java.lang.String getPeerURLs(int index) {
      return peerURLs_.get(index);
    }
    /**
     * <pre>
     * peerURLs is the list of URLs the member exposes to the cluster for communication.
     * </pre>
     *
     * <code>repeated string peerURLs = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the peerURLs at the given index.
     */
    public com.google.protobuf.ByteString
        getPeerURLsBytes(int index) {
      return peerURLs_.getByteString(index);
    }
    /**
     * <pre>
     * peerURLs is the list of URLs the member exposes to the cluster for communication.
     * </pre>
     *
     * <code>repeated string peerURLs = 3;</code>
     * @param index The index to set the value at.
     * @param value The peerURLs to set.
     * @return This builder for chaining.
     */
    public Builder setPeerURLs(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePeerURLsIsMutable();
      peerURLs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * peerURLs is the list of URLs the member exposes to the cluster for communication.
     * </pre>
     *
     * <code>repeated string peerURLs = 3;</code>
     * @param value The peerURLs to add.
     * @return This builder for chaining.
     */
    public Builder addPeerURLs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensurePeerURLsIsMutable();
      peerURLs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * peerURLs is the list of URLs the member exposes to the cluster for communication.
     * </pre>
     *
     * <code>repeated string peerURLs = 3;</code>
     * @param values The peerURLs to add.
     * @return This builder for chaining.
     */
    public Builder addAllPeerURLs(
        java.lang.Iterable<java.lang.String> values) {
      ensurePeerURLsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, peerURLs_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * peerURLs is the list of URLs the member exposes to the cluster for communication.
     * </pre>
     *
     * <code>repeated string peerURLs = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeerURLs() {
      peerURLs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * peerURLs is the list of URLs the member exposes to the cluster for communication.
     * </pre>
     *
     * <code>repeated string peerURLs = 3;</code>
     * @param value The bytes of the peerURLs to add.
     * @return This builder for chaining.
     */
    public Builder addPeerURLsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensurePeerURLsIsMutable();
      peerURLs_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList clientURLs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureClientURLsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        clientURLs_ = new com.google.protobuf.LazyStringArrayList(clientURLs_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * </pre>
     *
     * <code>repeated string clientURLs = 4;</code>
     * @return A list containing the clientURLs.
     */
    public com.google.protobuf.ProtocolStringList
        getClientURLsList() {
      return clientURLs_.getUnmodifiableView();
    }
    /**
     * <pre>
     * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * </pre>
     *
     * <code>repeated string clientURLs = 4;</code>
     * @return The count of clientURLs.
     */
    public int getClientURLsCount() {
      return clientURLs_.size();
    }
    /**
     * <pre>
     * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * </pre>
     *
     * <code>repeated string clientURLs = 4;</code>
     * @param index The index of the element to return.
     * @return The clientURLs at the given index.
     */
    public java.lang.String getClientURLs(int index) {
      return clientURLs_.get(index);
    }
    /**
     * <pre>
     * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * </pre>
     *
     * <code>repeated string clientURLs = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the clientURLs at the given index.
     */
    public com.google.protobuf.ByteString
        getClientURLsBytes(int index) {
      return clientURLs_.getByteString(index);
    }
    /**
     * <pre>
     * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * </pre>
     *
     * <code>repeated string clientURLs = 4;</code>
     * @param index The index to set the value at.
     * @param value The clientURLs to set.
     * @return This builder for chaining.
     */
    public Builder setClientURLs(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureClientURLsIsMutable();
      clientURLs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * </pre>
     *
     * <code>repeated string clientURLs = 4;</code>
     * @param value The clientURLs to add.
     * @return This builder for chaining.
     */
    public Builder addClientURLs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureClientURLsIsMutable();
      clientURLs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * </pre>
     *
     * <code>repeated string clientURLs = 4;</code>
     * @param values The clientURLs to add.
     * @return This builder for chaining.
     */
    public Builder addAllClientURLs(
        java.lang.Iterable<java.lang.String> values) {
      ensureClientURLsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, clientURLs_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * </pre>
     *
     * <code>repeated string clientURLs = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientURLs() {
      clientURLs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * clientURLs is the list of URLs the member exposes to clients for communication. If the member is not started, clientURLs will be empty.
     * </pre>
     *
     * <code>repeated string clientURLs = 4;</code>
     * @param value The bytes of the clientURLs to add.
     * @return This builder for chaining.
     */
    public Builder addClientURLsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureClientURLsIsMutable();
      clientURLs_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:etcdserverpb.Member)
  }

  // @@protoc_insertion_point(class_scope:etcdserverpb.Member)
  private static final org.eclipse.ecf.provider.etcd3.grpc.api.Member DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.eclipse.ecf.provider.etcd3.grpc.api.Member();
  }

  public static org.eclipse.ecf.provider.etcd3.grpc.api.Member getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Member>
      PARSER = new com.google.protobuf.AbstractParser<Member>() {
    @java.lang.Override
    public Member parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Member(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Member> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Member> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.eclipse.ecf.provider.etcd3.grpc.api.Member getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

