// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package org.eclipse.ecf.provider.etcd3.grpc.api;

public interface MoveLeaderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etcdserverpb.MoveLeaderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * targetID is the node ID for the new leader.
   * </pre>
   *
   * <code>uint64 targetID = 1;</code>
   * @return The targetID.
   */
  long getTargetID();
}
