// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package org.eclipse.ecf.provider.etcd3.grpc.api;

/**
 * Protobuf type {@code etcdserverpb.WatchCreateRequest}
 */
public final class WatchCreateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:etcdserverpb.WatchCreateRequest)
    WatchCreateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WatchCreateRequest.newBuilder() to construct.
  private WatchCreateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WatchCreateRequest() {
    key_ = com.google.protobuf.ByteString.EMPTY;
    rangeEnd_ = com.google.protobuf.ByteString.EMPTY;
    filters_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WatchCreateRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WatchCreateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            key_ = input.readBytes();
            break;
          }
          case 18: {

            rangeEnd_ = input.readBytes();
            break;
          }
          case 24: {

            startRevision_ = input.readInt64();
            break;
          }
          case 32: {

            progressNotify_ = input.readBool();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              filters_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            filters_.add(rawValue);
            break;
          }
          case 42: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                filters_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              filters_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          case 48: {

            prevKv_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        filters_ = java.util.Collections.unmodifiableList(filters_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_WatchCreateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_WatchCreateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.class, org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code etcdserverpb.WatchCreateRequest.FilterType}
   */
  public enum FilterType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * filter out put event.
     * </pre>
     *
     * <code>NOPUT = 0;</code>
     */
    NOPUT(0),
    /**
     * <pre>
     * filter out delete event.
     * </pre>
     *
     * <code>NODELETE = 1;</code>
     */
    NODELETE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * filter out put event.
     * </pre>
     *
     * <code>NOPUT = 0;</code>
     */
    public static final int NOPUT_VALUE = 0;
    /**
     * <pre>
     * filter out delete event.
     * </pre>
     *
     * <code>NODELETE = 1;</code>
     */
    public static final int NODELETE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FilterType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FilterType forNumber(int value) {
      switch (value) {
        case 0: return NOPUT;
        case 1: return NODELETE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FilterType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FilterType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FilterType>() {
            public FilterType findValueByNumber(int number) {
              return FilterType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final FilterType[] VALUES = values();

    public static FilterType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FilterType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:etcdserverpb.WatchCreateRequest.FilterType)
  }

  public static final int KEY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString key_;
  /**
   * <pre>
   * key is the key to register for watching.
   * </pre>
   *
   * <code>bytes key = 1;</code>
   * @return The key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getKey() {
    return key_;
  }

  public static final int RANGE_END_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString rangeEnd_;
  /**
   * <pre>
   * range_end is the end of the range [key, range_end) to watch. If range_end is not given,
   * only the key argument is watched. If range_end is equal to '&#92;0', all keys greater than
   * or equal to the key argument are watched.
   * If the range_end is one bit larger than the given key,
   * then all keys with the prefix (the given key) will be watched.
   * </pre>
   *
   * <code>bytes range_end = 2;</code>
   * @return The rangeEnd.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRangeEnd() {
    return rangeEnd_;
  }

  public static final int START_REVISION_FIELD_NUMBER = 3;
  private long startRevision_;
  /**
   * <pre>
   * start_revision is an optional revision to watch from (inclusive). No start_revision is "now".
   * </pre>
   *
   * <code>int64 start_revision = 3;</code>
   * @return The startRevision.
   */
  @java.lang.Override
  public long getStartRevision() {
    return startRevision_;
  }

  public static final int PROGRESS_NOTIFY_FIELD_NUMBER = 4;
  private boolean progressNotify_;
  /**
   * <pre>
   * progress_notify is set so that the etcd server will periodically send a WatchResponse with
   * no events to the new watcher if there are no recent events. It is useful when clients
   * wish to recover a disconnected watcher starting from a recent known revision.
   * The etcd server may decide how often it will send notifications based on current load.
   * </pre>
   *
   * <code>bool progress_notify = 4;</code>
   * @return The progressNotify.
   */
  @java.lang.Override
  public boolean getProgressNotify() {
    return progressNotify_;
  }

  public static final int FILTERS_FIELD_NUMBER = 5;
  private java.util.List<java.lang.Integer> filters_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType> filters_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType>() {
            public org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType result = org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType.valueOf(from);
              return result == null ? org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType.UNRECOGNIZED : result;
            }
          };
  /**
   * <pre>
   * filters filter the events at server side before it sends back to the watcher.
   * </pre>
   *
   * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
   * @return A list containing the filters.
   */
  @java.lang.Override
  public java.util.List<org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType> getFiltersList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType>(filters_, filters_converter_);
  }
  /**
   * <pre>
   * filters filter the events at server side before it sends back to the watcher.
   * </pre>
   *
   * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
   * @return The count of filters.
   */
  @java.lang.Override
  public int getFiltersCount() {
    return filters_.size();
  }
  /**
   * <pre>
   * filters filter the events at server side before it sends back to the watcher.
   * </pre>
   *
   * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
   * @param index The index of the element to return.
   * @return The filters at the given index.
   */
  @java.lang.Override
  public org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType getFilters(int index) {
    return filters_converter_.convert(filters_.get(index));
  }
  /**
   * <pre>
   * filters filter the events at server side before it sends back to the watcher.
   * </pre>
   *
   * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
   * @return A list containing the enum numeric values on the wire for filters.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
  getFiltersValueList() {
    return filters_;
  }
  /**
   * <pre>
   * filters filter the events at server side before it sends back to the watcher.
   * </pre>
   *
   * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of filters at the given index.
   */
  @java.lang.Override
  public int getFiltersValue(int index) {
    return filters_.get(index);
  }
  private int filtersMemoizedSerializedSize;

  public static final int PREV_KV_FIELD_NUMBER = 6;
  private boolean prevKv_;
  /**
   * <pre>
   * If prev_kv is set, created watcher gets the previous KV before the event happens.
   * If the previous KV is already compacted, nothing will be returned.
   * </pre>
   *
   * <code>bool prev_kv = 6;</code>
   * @return The prevKv.
   */
  @java.lang.Override
  public boolean getPrevKv() {
    return prevKv_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!key_.isEmpty()) {
      output.writeBytes(1, key_);
    }
    if (!rangeEnd_.isEmpty()) {
      output.writeBytes(2, rangeEnd_);
    }
    if (startRevision_ != 0L) {
      output.writeInt64(3, startRevision_);
    }
    if (progressNotify_ != false) {
      output.writeBool(4, progressNotify_);
    }
    if (getFiltersList().size() > 0) {
      output.writeUInt32NoTag(42);
      output.writeUInt32NoTag(filtersMemoizedSerializedSize);
    }
    for (int i = 0; i < filters_.size(); i++) {
      output.writeEnumNoTag(filters_.get(i));
    }
    if (prevKv_ != false) {
      output.writeBool(6, prevKv_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!key_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, key_);
    }
    if (!rangeEnd_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, rangeEnd_);
    }
    if (startRevision_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, startRevision_);
    }
    if (progressNotify_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, progressNotify_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < filters_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(filters_.get(i));
      }
      size += dataSize;
      if (!getFiltersList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }filtersMemoizedSerializedSize = dataSize;
    }
    if (prevKv_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, prevKv_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest)) {
      return super.equals(obj);
    }
    org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest other = (org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest) obj;

    if (!getKey()
        .equals(other.getKey())) return false;
    if (!getRangeEnd()
        .equals(other.getRangeEnd())) return false;
    if (getStartRevision()
        != other.getStartRevision()) return false;
    if (getProgressNotify()
        != other.getProgressNotify()) return false;
    if (!filters_.equals(other.filters_)) return false;
    if (getPrevKv()
        != other.getPrevKv()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    hash = (37 * hash) + RANGE_END_FIELD_NUMBER;
    hash = (53 * hash) + getRangeEnd().hashCode();
    hash = (37 * hash) + START_REVISION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartRevision());
    hash = (37 * hash) + PROGRESS_NOTIFY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getProgressNotify());
    if (getFiltersCount() > 0) {
      hash = (37 * hash) + FILTERS_FIELD_NUMBER;
      hash = (53 * hash) + filters_.hashCode();
    }
    hash = (37 * hash) + PREV_KV_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPrevKv());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code etcdserverpb.WatchCreateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:etcdserverpb.WatchCreateRequest)
      org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_WatchCreateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_WatchCreateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.class, org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.Builder.class);
    }

    // Construct using org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      key_ = com.google.protobuf.ByteString.EMPTY;

      rangeEnd_ = com.google.protobuf.ByteString.EMPTY;

      startRevision_ = 0L;

      progressNotify_ = false;

      filters_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      prevKv_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.ECFEtcdProto.internal_static_etcdserverpb_WatchCreateRequest_descriptor;
    }

    @java.lang.Override
    public org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest getDefaultInstanceForType() {
      return org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest build() {
      org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest buildPartial() {
      org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest result = new org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest(this);
      int from_bitField0_ = bitField0_;
      result.key_ = key_;
      result.rangeEnd_ = rangeEnd_;
      result.startRevision_ = startRevision_;
      result.progressNotify_ = progressNotify_;
      if (((bitField0_ & 0x00000001) != 0)) {
        filters_ = java.util.Collections.unmodifiableList(filters_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.filters_ = filters_;
      result.prevKv_ = prevKv_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest) {
        return mergeFrom((org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest other) {
      if (other == org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.getDefaultInstance()) return this;
      if (other.getKey() != com.google.protobuf.ByteString.EMPTY) {
        setKey(other.getKey());
      }
      if (other.getRangeEnd() != com.google.protobuf.ByteString.EMPTY) {
        setRangeEnd(other.getRangeEnd());
      }
      if (other.getStartRevision() != 0L) {
        setStartRevision(other.getStartRevision());
      }
      if (other.getProgressNotify() != false) {
        setProgressNotify(other.getProgressNotify());
      }
      if (!other.filters_.isEmpty()) {
        if (filters_.isEmpty()) {
          filters_ = other.filters_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureFiltersIsMutable();
          filters_.addAll(other.filters_);
        }
        onChanged();
      }
      if (other.getPrevKv() != false) {
        setPrevKv(other.getPrevKv());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * key is the key to register for watching.
     * </pre>
     *
     * <code>bytes key = 1;</code>
     * @return The key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }
    /**
     * <pre>
     * key is the key to register for watching.
     * </pre>
     *
     * <code>bytes key = 1;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * key is the key to register for watching.
     * </pre>
     *
     * <code>bytes key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString rangeEnd_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * range_end is the end of the range [key, range_end) to watch. If range_end is not given,
     * only the key argument is watched. If range_end is equal to '&#92;0', all keys greater than
     * or equal to the key argument are watched.
     * If the range_end is one bit larger than the given key,
     * then all keys with the prefix (the given key) will be watched.
     * </pre>
     *
     * <code>bytes range_end = 2;</code>
     * @return The rangeEnd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRangeEnd() {
      return rangeEnd_;
    }
    /**
     * <pre>
     * range_end is the end of the range [key, range_end) to watch. If range_end is not given,
     * only the key argument is watched. If range_end is equal to '&#92;0', all keys greater than
     * or equal to the key argument are watched.
     * If the range_end is one bit larger than the given key,
     * then all keys with the prefix (the given key) will be watched.
     * </pre>
     *
     * <code>bytes range_end = 2;</code>
     * @param value The rangeEnd to set.
     * @return This builder for chaining.
     */
    public Builder setRangeEnd(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rangeEnd_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * range_end is the end of the range [key, range_end) to watch. If range_end is not given,
     * only the key argument is watched. If range_end is equal to '&#92;0', all keys greater than
     * or equal to the key argument are watched.
     * If the range_end is one bit larger than the given key,
     * then all keys with the prefix (the given key) will be watched.
     * </pre>
     *
     * <code>bytes range_end = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRangeEnd() {
      
      rangeEnd_ = getDefaultInstance().getRangeEnd();
      onChanged();
      return this;
    }

    private long startRevision_ ;
    /**
     * <pre>
     * start_revision is an optional revision to watch from (inclusive). No start_revision is "now".
     * </pre>
     *
     * <code>int64 start_revision = 3;</code>
     * @return The startRevision.
     */
    @java.lang.Override
    public long getStartRevision() {
      return startRevision_;
    }
    /**
     * <pre>
     * start_revision is an optional revision to watch from (inclusive). No start_revision is "now".
     * </pre>
     *
     * <code>int64 start_revision = 3;</code>
     * @param value The startRevision to set.
     * @return This builder for chaining.
     */
    public Builder setStartRevision(long value) {
      
      startRevision_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * start_revision is an optional revision to watch from (inclusive). No start_revision is "now".
     * </pre>
     *
     * <code>int64 start_revision = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartRevision() {
      
      startRevision_ = 0L;
      onChanged();
      return this;
    }

    private boolean progressNotify_ ;
    /**
     * <pre>
     * progress_notify is set so that the etcd server will periodically send a WatchResponse with
     * no events to the new watcher if there are no recent events. It is useful when clients
     * wish to recover a disconnected watcher starting from a recent known revision.
     * The etcd server may decide how often it will send notifications based on current load.
     * </pre>
     *
     * <code>bool progress_notify = 4;</code>
     * @return The progressNotify.
     */
    @java.lang.Override
    public boolean getProgressNotify() {
      return progressNotify_;
    }
    /**
     * <pre>
     * progress_notify is set so that the etcd server will periodically send a WatchResponse with
     * no events to the new watcher if there are no recent events. It is useful when clients
     * wish to recover a disconnected watcher starting from a recent known revision.
     * The etcd server may decide how often it will send notifications based on current load.
     * </pre>
     *
     * <code>bool progress_notify = 4;</code>
     * @param value The progressNotify to set.
     * @return This builder for chaining.
     */
    public Builder setProgressNotify(boolean value) {
      
      progressNotify_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * progress_notify is set so that the etcd server will periodically send a WatchResponse with
     * no events to the new watcher if there are no recent events. It is useful when clients
     * wish to recover a disconnected watcher starting from a recent known revision.
     * The etcd server may decide how often it will send notifications based on current load.
     * </pre>
     *
     * <code>bool progress_notify = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearProgressNotify() {
      
      progressNotify_ = false;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> filters_ =
      java.util.Collections.emptyList();
    private void ensureFiltersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        filters_ = new java.util.ArrayList<java.lang.Integer>(filters_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     * @return A list containing the filters.
     */
    public java.util.List<org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType> getFiltersList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType>(filters_, filters_converter_);
    }
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     * @return The count of filters.
     */
    public int getFiltersCount() {
      return filters_.size();
    }
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     * @param index The index of the element to return.
     * @return The filters at the given index.
     */
    public org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType getFilters(int index) {
      return filters_converter_.convert(filters_.get(index));
    }
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     * @param index The index to set the value at.
     * @param value The filters to set.
     * @return This builder for chaining.
     */
    public Builder setFilters(
        int index, org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureFiltersIsMutable();
      filters_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     * @param value The filters to add.
     * @return This builder for chaining.
     */
    public Builder addFilters(org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureFiltersIsMutable();
      filters_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     * @param values The filters to add.
     * @return This builder for chaining.
     */
    public Builder addAllFilters(
        java.lang.Iterable<? extends org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType> values) {
      ensureFiltersIsMutable();
      for (org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest.FilterType value : values) {
        filters_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilters() {
      filters_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     * @return A list containing the enum numeric values on the wire for filters.
     */
    public java.util.List<java.lang.Integer>
    getFiltersValueList() {
      return java.util.Collections.unmodifiableList(filters_);
    }
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of filters at the given index.
     */
    public int getFiltersValue(int index) {
      return filters_.get(index);
    }
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of filters at the given index.
     * @return This builder for chaining.
     */
    public Builder setFiltersValue(
        int index, int value) {
      ensureFiltersIsMutable();
      filters_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     * @param value The enum numeric value on the wire for filters to add.
     * @return This builder for chaining.
     */
    public Builder addFiltersValue(int value) {
      ensureFiltersIsMutable();
      filters_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * filters filter the events at server side before it sends back to the watcher.
     * </pre>
     *
     * <code>repeated .etcdserverpb.WatchCreateRequest.FilterType filters = 5;</code>
     * @param values The enum numeric values on the wire for filters to add.
     * @return This builder for chaining.
     */
    public Builder addAllFiltersValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureFiltersIsMutable();
      for (int value : values) {
        filters_.add(value);
      }
      onChanged();
      return this;
    }

    private boolean prevKv_ ;
    /**
     * <pre>
     * If prev_kv is set, created watcher gets the previous KV before the event happens.
     * If the previous KV is already compacted, nothing will be returned.
     * </pre>
     *
     * <code>bool prev_kv = 6;</code>
     * @return The prevKv.
     */
    @java.lang.Override
    public boolean getPrevKv() {
      return prevKv_;
    }
    /**
     * <pre>
     * If prev_kv is set, created watcher gets the previous KV before the event happens.
     * If the previous KV is already compacted, nothing will be returned.
     * </pre>
     *
     * <code>bool prev_kv = 6;</code>
     * @param value The prevKv to set.
     * @return This builder for chaining.
     */
    public Builder setPrevKv(boolean value) {
      
      prevKv_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If prev_kv is set, created watcher gets the previous KV before the event happens.
     * If the previous KV is already compacted, nothing will be returned.
     * </pre>
     *
     * <code>bool prev_kv = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrevKv() {
      
      prevKv_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:etcdserverpb.WatchCreateRequest)
  }

  // @@protoc_insertion_point(class_scope:etcdserverpb.WatchCreateRequest)
  private static final org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest();
  }

  public static org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WatchCreateRequest>
      PARSER = new com.google.protobuf.AbstractParser<WatchCreateRequest>() {
    @java.lang.Override
    public WatchCreateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WatchCreateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WatchCreateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WatchCreateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.eclipse.ecf.provider.etcd3.grpc.api.WatchCreateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

